services:
  spring-boot-docker:
    container_name: spring-boot-docker-container
    build:
      context: .
      args:
        HOST_PORT: ${HOST_PORT}
    image: spring-boot-docker:v1.0.0
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    expose:
      - ${HOST_PORT}
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
